package ligamx.controller;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import ligamx.dto.EquipoDTO;
import ligamx.dto.PartidoDTO;
import ligamx.service.EquipoService;
import ligamx.service.PartidoService;
import ligamx.service.impl.EquipoServiceImpl;
import ligamx.service.impl.PartidoServiceImpl;
import ligamx.util.ExcepcionAplicacion;
import ligamx.util.LongTaskGrafica;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author hecto
 */
public class Grafica extends javax.swing.JPanel {

    protected static final org.apache.logging.log4j.Logger LOGGER = LogManager.getLogger();
    private final EquipoService equipoService = new EquipoServiceImpl();
    private final PartidoService partidoService = new PartidoServiceImpl();
    private static LongTaskGrafica task;

    /**
     * Creates new form Grafica
     *
     * @param task
     */
    public Grafica(LongTaskGrafica task) {
        initComponents();
        Grafica.task = task;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrafica = new javax.swing.JTable();

        tblGrafica.setAutoCreateRowSorter(true);
        tblGrafica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Equipo/Jornada ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17"
            }
        ) {
            Class[] types = new Class [] {
                javax.swing.ImageIcon.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGrafica.setRowHeight(17);
        tblGrafica.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblGrafica);
        tblGrafica.setRowHeight(17);
        if (tblGrafica.getColumnModel().getColumnCount() > 0) {
            tblGrafica.getColumnModel().getColumn(0).setResizable(false);
            tblGrafica.getColumnModel().getColumn(0).setPreferredWidth(17);
            tblGrafica.getColumnModel().getColumn(1).setResizable(false);
            tblGrafica.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblGrafica.getColumnModel().getColumn(2).setResizable(false);
            tblGrafica.getColumnModel().getColumn(3).setResizable(false);
            tblGrafica.getColumnModel().getColumn(4).setResizable(false);
            tblGrafica.getColumnModel().getColumn(5).setResizable(false);
            tblGrafica.getColumnModel().getColumn(6).setResizable(false);
            tblGrafica.getColumnModel().getColumn(7).setResizable(false);
            tblGrafica.getColumnModel().getColumn(8).setResizable(false);
            tblGrafica.getColumnModel().getColumn(9).setResizable(false);
            tblGrafica.getColumnModel().getColumn(10).setResizable(false);
            tblGrafica.getColumnModel().getColumn(11).setResizable(false);
            tblGrafica.getColumnModel().getColumn(12).setResizable(false);
            tblGrafica.getColumnModel().getColumn(13).setResizable(false);
            tblGrafica.getColumnModel().getColumn(14).setResizable(false);
            tblGrafica.getColumnModel().getColumn(15).setResizable(false);
            tblGrafica.getColumnModel().getColumn(16).setResizable(false);
            tblGrafica.getColumnModel().getColumn(17).setResizable(false);
            tblGrafica.getColumnModel().getColumn(18).setResizable(false);
        }
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) tblGrafica.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tblGrafica.setDefaultRenderer(Integer.class, centerRenderer);
        tblGrafica.setDefaultRenderer(String.class, centerRenderer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void llenarTabla() {
        Integer current = 0;
        try {
            List<EquipoDTO> equiposList = equipoService.buscarEquipos();
            for (int fila = 0; fila < equiposList.size(); fila++) {
                String nombre = equiposList.get(fila).getNombre();
                tblGrafica.setValueAt(nombre, fila, 1);
                String url = "ligamx/resources/images/" + nombre + ".png";
                ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource(url)));
                icon.setImage(icon.getImage().getScaledInstance(17, 17, Image.SCALE_DEFAULT));
                tblGrafica.setValueAt(icon, fila, 0);
                task.setCurrent(++current);
            }
            for (int jornada = 1; jornada <= 17; jornada++) {
                for (EquipoDTO equipoDTO : equiposList) {
                    List<PartidoDTO> partidos = partidoService.buscarPartidosGrafica(jornada, equipoDTO);
                    Integer jg = 0;
                    Integer je = 0;
                    Integer pts;
                    for (PartidoDTO partido : partidos) {
                        if (partido.getIdLocal().equals(equipoDTO.getIdEquipo()) && null != partido.getMl() && null != partido.getMv()) {
                            if (partido.getMl().compareTo(partido.getMv()) > 0) {
                                jg++;
                            } else if (partido.getMl().equals(partido.getMv())) {
                                je++;
                            }
                        } else if (partido.getMl().compareTo(partido.getMv()) < 0) {
                            jg++;
                        } else if (partido.getMl().equals(partido.getMv())) {
                            je++;
                        }
                    }
                    pts = jg * 3 + je;
                    tblGrafica.setValueAt(pts, equiposList.indexOf(equipoDTO), jornada + 1);
                    task.setCurrent(++current);
                }
            }
            //task.setCurrent(5220);
        } catch (ExcepcionAplicacion ex) {
            LOGGER.error(ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGrafica;
    // End of variables declaration//GEN-END:variables
}
